version: '3'
services:
  web:
    image: nginx:alpine
    ports:
      - "7060:80"
    volumes:
      - .:/var/www/html
      - ./site.conf:/etc/nginx/conf.d/default.conf

  php:
    build:
      context: .
      args:
        - INSTALL_XDEBUG=${INSTALL_XDEBUG}
    expose:
      - "9000"
    volumes:
      - .:/var/www/html
    environment:
      - XDEBUG_CONFIG=remote_host=${IP}
      - DEBUG=${DEBUG:-0}